# Generated by Django 5.1.2 on 2024-10-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_description_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='games/default_game_image.jpg', upload_to='games/'),
        ),
    ]
